/**
 * Real tattoo work by Younes, photographed as delivered. No client names,
 * dates, placements or descriptions have been supplied, so each piece only
 * carries a neutral number/label - replace `label` (and add fields) when the
 * real information exists. Do not invent it.
 *
 * `src` is the untouched original in public/work/. The gallery serves the
 * WebP copies in public/work/web/ generated by scripts/build-work-images.py;
 * `widths` lists which exist. Order here is the order of the archive.
 */
export type WorkAspect = 'square' | 'portrait' | 'tall';

export interface WorkPiece {
  id: string;
  /** file stem in public/work/ */
  file: string;
  src: string;
  width: number;
  height: number;
  aspect: WorkAspect;
  /** widths available in public/work/web/<file>-<w>.webp */
  widths: number[];
  /** neutral label shown beside the number, e.g. "Tattoo study" + "01" */
  label: string;
}

type Source = Pick<WorkPiece, 'file' | 'width' | 'height' | 'widths'> & { ext: string };

const SOURCES: Source[] = [
  { file: 'portrait-02', ext: 'JPG', width: 1125, height: 1406, widths: [640, 1125] },
  { file: 'square-01', ext: 'JPG', width: 1125, height: 1125, widths: [640, 1125] },
  { file: 'vertical-03', ext: 'png', width: 941, height: 1672, widths: [640, 941] },
  { file: 'portrait-01', ext: 'JPG', width: 1125, height: 1406, widths: [640, 1125] },
  { file: 'vertical-01', ext: 'JPG', width: 1125, height: 2000, widths: [640, 1125] },
  { file: 'vertical-02', ext: 'png', width: 649, height: 1154, widths: [649] },
  { file: 'square-02', ext: 'JPG', width: 1125, height: 1125, widths: [640, 1125] },
  { file: 'portrait-03', ext: 'JPG', width: 1125, height: 1406, widths: [640, 1125] },
];

function aspectOf(width: number, height: number): WorkAspect {
  const r = width / height;
  if (r > 0.95) return 'square';
  if (r > 0.7) return 'portrait';
  return 'tall';
}

export const WORK: WorkPiece[] = SOURCES.map(({ ext, ...s }, i) => {
  const id = String(i + 1).padStart(2, '0');
  return {
    ...s,
    id,
    src: `/work/${s.file}.${ext}`,
    aspect: aspectOf(s.width, s.height),
    label: 'Tattoo study',
  };
});

/** e.g. 4:5 - factual, shown as contact-sheet metadata */
export const RATIO_LABEL: Record<WorkAspect, string> = { square: '1:1', portrait: '4:5', tall: '9:16' };

export function workAlt(piece: WorkPiece): string {
  return `${piece.label} ${piece.id} - tattoo by Younes`;
}

export function workSrcSet(piece: WorkPiece): string {
  return piece.widths.map((w) => `/work/web/${piece.file}-${w}.webp ${w}w`).join(', ');
}

/** the largest web copy - what the viewer shows */
export function workLargest(piece: WorkPiece): string {
  return `/work/web/${piece.file}-${piece.widths[piece.widths.length - 1]}.webp`;
}
